In [23]:
import pandas as pd
from sdv.single_table import CTGANSynthesizer, GaussianCopulaSynthesizer
from sdv.metadata import Metadata

In [15]:
data = pd.read_csv('adult_census.csv')
real_data = data.sample(n=2000, random_state=42).reset_index(drop=True)
real_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,27,Private,160178,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,38,United-States,<=50K
1,45,State-gov,50567,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
2,29,Private,185908,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,55,United-States,>50K
3,30,Private,190040,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
4,29,Self-emp-not-inc,189346,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,2202,0,50,United-States,<=50K

In [16]:
metadata = Metadata.detect_from_dataframe(real_data)

In [18]:
metadata.save_to_json('metadata.json')

In [24]:
synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(real_data)
synthetic_data = synthesizer.sample(2000)
synthetic_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,Private,220539,9th,2,Married-civ-spouse,Exec-managerial,Not-in-family,Black,Male,2,2221,42,United-States,<=50K
1,54,Private,90861,HS-grad,2,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,1924,42,Iran,<=50K
2,20,Private,223117,HS-grad,2,Never-married,Exec-managerial,Unmarried,White,Female,0,2009,42,United-States,>50K
3,26,Private,153369,Bachelors,2,Married-civ-spouse,Craft-repair,Not-in-family,White,Male,0,1967,42,United-States,<=50K
4,19,Private,224088,10th,2,Married-civ-spouse,Farming-fishing,Own-child,White,Male,9,1800,42,United-States,<=50K

In [25]:
from sdv.evaluation.single_table import run_diagnostic
diagnostic = run_diagnostic(
    real_data=real_data,
    synthetic_data=synthetic_data,
    metadata=metadata
)

Generating report ...

(1/2) Evaluating Data Validity: |████████████| 15/15 [00:00<00:00, 1065.03it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████████| 1/1 [00:00<00:00, 338.30it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

In [26]:
from sdv.evaluation.single_table import evaluate_quality

quality_report = evaluate_quality(
    real_data,
    synthetic_data,
    metadata
)

Generating report ...

(1/2) Evaluating Column Shapes: |█████████████| 15/15 [00:00<00:00, 617.34it/s]|
Column Shapes Score: 77.84%

(2/2) Evaluating Column Pair Trends: |██████| 105/105 [00:00<00:00, 788.21it/s]|
Column Pair Trends Score: 66.66%

Overall Score (Average): 72.25%

In [27]:
from sdv.evaluation.single_table import get_column_plot

fig = get_column_plot(
    real_data=real_data,
    synthetic_data=synthetic_data,
    column_name='occupation',
    metadata=metadata
)

fig.show()